baseurl: ''
domain: realestate.net.ua
url: 'https://www.realestate.net.ua'

encoding: UTF-8
lang: uk_UA
timezone: Europe/Kyiv
country: Україна
region: Україна
region_size: .89rem

usd: 38.70
eur: 42.40

title: Мережа Вебсайтів Нерухомості
keywords: житло, квартира, нерухомість продам будинок, продаю гараж, продаємо житло, здається квартира, продаж житла, оренда квартир, квартира подобово, продати будинок, продамо землю, земля продається, продаю квартиру, здаю житло
description: Безкоштовні оголошення про купівлю і продаж та оренду квартир, будинків і землі та нежитлової нерухомості, що будуються, продаються або передаються в оренду в межах України
name: Регіональна нерухомість
brand: Нерухомість
logo: '/assets/images/logo.svg'

author:
  name: Vasyl&nbsp;Mosiychuk
  website: http://www.vasyl.net
  email: info@vasyl.net
developer:
  name: vasyl.net
  website: http://www.vasyl.net
  email: info@vasyl.net

contact:
  name: Мережа Вебсайтів Нерухомості в&nbsp;Україні
  address: 76018, м. Івано-Франківськ, вул.&nbsp;Січових&nbsp;Стрільців,&nbsp;56
  phone_main: 380974949649
  phone_hot: 380974949649
  phone_fax: 380974949649
  phone_sms: 380504949649
  phone_advert: 380504949649
  phone_buy_sell: 380974949649
  phone_add_ads: 380504949649
  phone_submit_ads: 380504949649
  phone_support: 380504949649
  phone_buy: 380974949649
  phone_sell: 380974949649
  email: info@realestate.net.ua
  www: https://www.realestate.net.ua/

safe: true

markdown: kramdown
kramdown:
  auto_ids: false

# Handling Reading
safe: false
include:
  - .htaccess
exclude:
  - .gitignore
  - README.md
  - node_modules
  - .sass-cashe
  - Gemfile
  - Gemfile.lock
  - .git/
  - Gruntfile.js
  - package.json

collections:
  help:
    output: true
  stabs:
    output: true
  otabs:
    output: true
  owners:
    output: true

defaults:
  - scope:
      path: /*/data/*.json
    values:
      layout: "null"
      sitemap: false
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout:

plugins:
  - jekyll-compress-images
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-get-json

imageoptim:
  pngout: false
  svgo: true
  verbose: false

pagination:
  enabled: true
  per_page: 6
  permalink: '/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

jekyll_get_json:
  # Get all
  - data: ltua
    json: 'https://www.realestate.lt.ua/region/volynska/data/all.json'
    cache: true
  - data: uzua
    json: 'https://www.realestate.uz.ua/region/zakarpatska/data/all.json'
    cache: true
  - data: odua
    json: 'https://www.realestate.od.ua/region/odeska/data/all.json'
    cache: true
  - data: cvua
    json: 'https://www.realestate.cv.ua/region/chernivetska/data/all.json'
    cache: true
  # Get options
  - data: kyiv
    json: 'https://www.realestate.kyiv.ua/region/data/options.json'
    cache: true
  - data: if
    json: 'https://www.realestate.if.ua/region/data/options.json'
    cache: true
  - data: te
    json: 'https://www.realestate.te.ua/region/data/options.json'
    cache: true
  - data: in
    json: 'https://www.realestate.in.ua/region/data/options.json'
    cache: true
  - data: uz
    json: 'https://www.realestate.uz.ua/region/data/options.json'
    cache: true
  - data: od
    json: 'https://www.realestate.od.ua/region/data/options.json'
    cache: true
  - data: zp
    json: 'https://www.realestate.zp.ua/region/data/options.json'
    cache: true
  - data: lt
    json: 'https://www.realestate.lt.ua/region/data/options.json'
    cache: true
  - data: kh
    json: 'https://www.realestate.kh.ua/region/data/options.json'
    cache: true
  - data: cv
    json: 'https://www.realestate.cv.ua/region/data/options.json'
    cache: true

sass:
  sass_dir: _sass
  style: compressed

compress_images:
  images_path: "assets/images/**/*.{png,jpg,jpeg,svg}"

compress_html:
  clippings: all
  comments: [""]
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []
